### PR TITLE
Updated to 1.19, using gradle, and some small refactors

### PR DESCRIPTION
**Pull request by powerje**
Updated this to use in my own game, making a PR in case you'd like to have the changes as well

### CODE REVIEW

**Comment by oddstr13** [comment]
This PR is incredibly difficult to review due to the sheer amount of changes made, and unlikely to get merged due to complete change in tooling and such. (I'm just a random passer-by, not a maintainer of *this* project.)

This PR should be broken out to *at least* 5 different PRs (just for reference when contributing to open source projects in the future).
- The 1.19 changes
- Addition of gradle tooling
- Code cleanup changes (final, not null etc)
- Addition of IntelliJ configs (and *maybe* removal of Eclipse, probably best as a separate PR too)
- Styling changes (tab -> spaces etc.)

It is pretty much impossible to discern the functional changes (for 1.19) in this PR due to all the noise generated by the change of indentation, addition of final keyword, change of variable names etc.

I *do* see that you're making the PR from your main branch, so maybe much of this was accidental from your part? :sweat_smile:

**Comment by powerje** [comment]
@oddstr13 thank you for your comment :)

When I made the PR, I was unsure if the project was being actively maintained. This was not accidental; it was more that I did not expect there to be much interest in the changes being merged. I hoped that if other folks wanted to use the plugin in newer versions of Minecraft, they could use my changes.

You make really good points, though. I should have put a bit more effort into this, and maybe that would make the project owner more interested in accepting my changes!

I think many of the things I had here were done in [a separate PR](https://github.com/rmellis/MinecartSpeedPlus/pull/2) that was merged, so probably fine to close mine anyway.

**Comment by oddstr13** [comment]
Yea, after having further examined the project I've come to the conclusion that this particular PR doesn't really add much to the project right now :)

Working on customizing it for my own server right now, and I don't think it makes sense to merge most of that upstream either, as it turns out I'm essentially rewriting most of the plugin. (you can follow along at https://github.com/UrbanCraft/MinecartSpeedPlus/commits/oddchoices/ if you're interested).
I might end up publishing a hard fork if I get it working as I want.

**Comment by powerje** [comment]
Nice, sounds fun!

If you're interested, it looks like there is a blessed fork: https://github.com/rmellis/MinecartSpeedPlus/issues/5#issuecomment-1828845197 (https://github.com/TravorLZH/MinecartSpeedPlus/releases), though based on your changes I think you'll probably be happier going forward with your own updates.

**Pull request closed without merging**
